services:
  app:
    build: .
    image: mtakemi/ubuntu-x11-apps:gpu-viewer
    ipc: host
    devices:
      - /dev/dxg:/dev/dxg
    volumes:
      - /usr/lib/wsl:/usr/lib/wsl
      - /mnt/wslg:/mnt/wslg
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      DISPLAY: :0
      WAYLAND_DISPLAY: wayland-0
      XDG_RUNTIME_DIR: /mnt/wslg/runtime-dir
      GALLIUM_DRIVER: d3d12
      MESA_LOADER_DRIVER_OVERRIDE: d3d12
      MESA_D3D12_DEFAULT_ADAPTER_NAME: NVIDIA
      VK_ICD_FILENAMES: /usr/share/vulkan/icd.d/dzn_icd.json
      VK_DRIVER_FILES: /usr/share/vulkan/icd.d/dzn_icd.json
      LIBVA_DRIVER_NAME: d3d12
      PULSE_SERVER: /mnt/wslg/PulseServer
      LD_LIBRARY_PATH: /usr/lib/wsl/lib
    tty: true
    stdin_open: true
    command: /bin/bash -c 'glxinfo -B && gpu-viewer'
